### ISSUE TITLE
Size of Intro container on big screen is almost too big

### ISSUE THREAD

**Issue by sheilabrennan** [chnm/rrchnm2016#14]
It feels yuge on a laptop screen. I like how responds, and looks better in a mobile view. 
Can the height proportion be reduced for full screen views?

Interested in hearing other opinions.

**Comment by kschrum** [comment]
Agreed - can we make these smaller universally? I like that it draws your attention, but the grey box and short text is the main thing you see. Our work, our people, etc. is getting lost a bit.

**Comment by kimisgold** [comment]
It's as big as it is because it's meant to include photos, and shorter heights create odd aspect ratios. On pages where users will spend a lot of time (essays, blog posts), I condense these sections or don't include this style entirely. I feel like it'd be less awkward if we had more photos uploaded, but I haven't heard any updates on #31.
