### ISSUE TITLE
Second section of Home Page

### ISSUE THREAD

**Issue by srob4757** [chnm/rrchnm2016#23]
I'm a bit confused by this section - I'm not sure we need most of it here. 
- Follow us -- the Hub will provide that info. 
- About Us - that column replicates Our Story. 
- Tools - do we need a shortcut to these on the home page, as opposed to via What We Do?

We do need a place for "Support the Center" - and as much as we want people to do this, I'm happy for it not to be in the top Menu (I think a Support the Center link should be at the end of the text on the Our Story page, in addition to a Contact Us link)

**Comment by kimisgold** [comment]
Follow Us and Tools: I think having individual links to specific social media platforms and RRCHM tools on the homepage is fine, especially since "The Hub" and "What We Do" will be aggregations of their respective content—if people want a specific platform, this gives them a one-click option from the homepage.

I agree that About Us seems unnecessary, especially since the individual links are one-sentence lines on that page. We could link to a "Support the Center" page in that space.

**Comment by srob4757** [comment]
OK, let's cut About Us and put Support the Center in that space.

A thought on Tools - should that be Featured Projects (and echo the Featured Projects tag on What We Do)? I.e. I can't think of a reason to focus on tools and not more broadly on our most popular sites

**Comment by kimisgold** [comment]
Do we have content for Support the Center?

**Comment by srob4757** [comment]
The CHSS Development office is working on this. In the meantime, we can use the existing link: https://securemason.gmu.edu/s/1564/match/index-1col.aspx?sid=1564&gid=2&pgid=651&cid=1709&dids=176&appealcode=IHM01

**Comment by kimisgold** [comment]
The home page has been updated according to the directors' content document.
