### ISSUE TITLE
Featured image size

### ISSUE THREAD

**Issue by kschrum** [chnm/rrchnm2016#45]
Can you post the recommended size for featured images?

**Comment by kimisgold** [comment]
I think we're going to go forward with two images per project: a logo/thumbnail image and a cover image. 

**The logo/thumbnail image**: This will be what represents the project on 'What We Do'. To avoid having to reupload all of these, I think keeping to the 270x90 standard set previously should be fine. I would recommend uploading these via the Media library, and then copying the URL into a custom field on the project page using the field name 'Image'.

**Cover image**: This will be what appears behind the title on individual project pages. These backgrounds should be colorful imagery related to the project, not limited to screenshots or logos. Shoot for 1280px in width, and the height can be variable since this is a responsive container that will scale. These photos should be landscape orientation, so greater width than height. Upload these on a project page using the "Featured Image" interface.

I'll repost this information to a wiki page for future reference, along with more screenshots.

**Comment by kimisgold** [comment]
The wiki page is here: https://github.com/chnm/rrchnm2016/wiki/Populating-Project-Pages.
